version: '3'

volumes:
  elasticsearch_data:

services:
  elasticsearch:
    image: elasticsearch:5
    command: "-E network.host=0.0.0.0 -E discovery.zen.minimum_master_nodes=1"
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Des.path.conf=/etc/elasticsearch"
  logstash:
    image: logstash:5
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/templates:/templates
    depends_on:
      - elasticsearch
    networks:
      - outside
      - default
  kibana:
    image: kibana:5
    volumes:
      - ./kibana/config/:/etc/kibana/
    networks:
      - outside
      - default
    depends_on:
      - elasticsearch

networks:
  default:
    driver: overlay
  outside:
    external:
      name: rp
